#!/usr/bin/env python

import datetime
import csv
import tarfile
import os
import sys
from os.path import *
import xml.etree.ElementTree as xml
import subprocess

description = r"""
	SRA Quick Submit
	Aug 16, Justin Payne 
	ORISE FDA-CFSAN-ORS-DM-MMSB
	justin.payne@fda.hhs.gov
	v1.5b
	
Import a table file of metadata or a MiSeq output directory and generate 
submittable XML tarballs that can be uploaded to NCBI SRA. Accepts any line
ending (Mac, PC, Linux)."""

change_history = """
Change history:
Aug 29 v1.1b: protection from sample name collision. 
Sep 6  v1.2b: -p flag for specifying BioProject ID.
Sep 16 v1.5b:  release version for GenomeTrakr community.
"""



experiment = """
<EXPERIMENT alias="{Sample Name}" xmlns="" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<TITLE>Whole genome shotgun sequencing of {organism} by Illumina MiSeq</TITLE>
	<STUDY_REF accession="{project}" />
	<DESIGN>
      <DESIGN_DESCRIPTION>MiSeq deep shotgun sequencing of cultured isolate.</DESIGN_DESCRIPTION>
      <SAMPLE_DESCRIPTOR accession="{Biosample Accession}" />
      <LIBRARY_DESCRIPTOR>
        <LIBRARY_NAME>{organism} Nextera XT shotgun library</LIBRARY_NAME>
        <LIBRARY_STRATEGY>WGS</LIBRARY_STRATEGY>
        <LIBRARY_SOURCE>GENOMIC</LIBRARY_SOURCE>
        <LIBRARY_SELECTION>RANDOM</LIBRARY_SELECTION>
        <LIBRARY_LAYOUT>
          <PAIRED NOMINAL_LENGTH="500" />
        </LIBRARY_LAYOUT>
        <LIBRARY_CONSTRUCTION_PROTOCOL>Illumina Nextera XT library created for {organism}.</LIBRARY_CONSTRUCTION_PROTOCOL>
      </LIBRARY_DESCRIPTOR>
      <SPOT_DESCRIPTOR>
              <SPOT_DECODE_SPEC>
                <SPOT_LENGTH>502</SPOT_LENGTH>
                <READ_SPEC>
                  <READ_INDEX>0</READ_INDEX>
                  <READ_CLASS>Application Read</READ_CLASS>
                  <READ_TYPE>Forward</READ_TYPE>
                  <BASE_COORD>1</BASE_COORD>
                </READ_SPEC>
                <READ_SPEC>
                  <READ_INDEX>1</READ_INDEX>
                  <READ_CLASS>Application Read</READ_CLASS>
                  <READ_TYPE>Reverse</READ_TYPE>
                  <BASE_COORD>251</BASE_COORD>
                </READ_SPEC>
              </SPOT_DECODE_SPEC>
      </SPOT_DESCRIPTOR>
    </DESIGN>
	<PLATFORM>
		<ILLUMINA>
			<INSTRUMENT_MODEL>Illumina MiSeq</INSTRUMENT_MODEL>
		</ILLUMINA>
	</PLATFORM>
	<PROCESSING>
		<PIPELINE>
			<PIPE_SECTION section_name="base caller">
				<STEP_INDEX>0</STEP_INDEX>
			   	<PREV_STEP_INDEX>NULL</PREV_STEP_INDEX>
			   	<PROGRAM>RTA</PROGRAM>
			   	<VERSION>{version}</VERSION>
			</PIPE_SECTION>
		</PIPELINE>
	</PROCESSING>
</EXPERIMENT>
"""

run = """
<RUN alias="{Sample Name}">
 <EXPERIMENT_REF refname="{Sample Name}" />
 <DATA_BLOCK>
  <FILES>
  	<FILE checksum_method="MD5" filetype="fastq" checksum="{file1_checksum}" filename="{file1_name}" />
  	<FILE checksum_method="MD5" filetype="fastq" checksum="{file2_checksum}" filename="{file2_name}" />
  </FILES>
 </DATA_BLOCK>
</RUN>
"""

submission = """
<SUBMISSION alias="{Sample Name}{num}" submission_comment="GenomeTrakr pathogen sampling project">	
	<CONTACTS>
		<CONTACT inform_on_error="mailto:{email}" inform_on_status="{email}" name="{name}" />
	</CONTACTS>
	<ACTIONS>
	<ACTION><ADD schema="experiment" source="{Sample Name}{num}.experiment.xml" /></ACTION>
	<ACTION><ADD schema="run" source="{Sample Name}{num}.run.xml" /></ACTION>
	<ACTION><HOLD HoldUntilDate="{date}Z" /></ACTION></ACTIONS>
</SUBMISSION>
"""

sample_names = list()

def make_submission(path, entry, project, hold, **kwargs):
	"Produce three submission files - run, experiment, submission - and then tar them up."
	print "Producing run, experiment, and submission file for sample {Sample Name}...".format(**entry)
	
	entry.update(kwargs)
	
	if entry['Sample Name'] in sample_names:
		entry['num'] = ".{:02}".format(sample_names.count(entry['Sample Name']) + 1)
	else:
		entry['num'] = ''
	
	try:
		if not exists(path):
			os.makedirs(path)
			print "Made {}.".format(path)
		exp = xml.fromstring(experiment.format(project=project, **entry))
		xml.ElementTree(exp).write(join(path, '{Sample Name}{num}.experiment.xml'.format(**entry)), encoding="UTF-8", xml_declaration=True)
	
		r = xml.fromstring(run.format(**entry))
		xml.ElementTree(r).write(join(path, '{Sample Name}{num}.run.xml'.format(**entry)), encoding="UTF-8", xml_declaration=True)
	
		sub = xml.fromstring(submission.format(date=hold, **entry))
		xml.ElementTree(sub).write(join(path, '{Sample Name}{num}.submission.xml'.format(**entry)), encoding="UTF-8", xml_declaration=True)
	except xml.ParseError as e:
		print "XML internal parsing failed. Tried to parse:"
		print experiment.format(project=project, **entry)
		print run.format(**entry)
		print submission.format(date=date, **entry)
		raise e
	tarball = tarfile.open(join(path, '{Sample Name}{num}.submission_archive.tar'.format(**entry)), 'w', format=tarfile.GNU_FORMAT)
	tarball.add(join(path, '{Sample Name}{num}.experiment.xml'.format(**entry)), arcname='{Sample Name}{num}.experiment.xml'.format(**entry))
	tarball.add(join(path, '{Sample Name}{num}.run.xml'.format(**entry)), arcname='{Sample Name}{num}.run.xml'.format(**entry))
	tarball.add(join(path, '{Sample Name}{num}.submission.xml'.format(**entry)), arcname='{Sample Name}{num}.submission.xml'.format(**entry))
	tarball.close()
	sample_names.append(entry['Sample Name'])
	
def process_miseq_output(input_dir, output_dir, project=False, callback=lambda l: None, **kwargs):
	import hashlib
	run_params = xml.parse(join(input_dir, 'RunParameters.xml'))
	version = run_params.find('.//RTAVersion').text
	with open(join(input_dir, 'SampleSheet.csv'), 'rU') as samplesheet:
		for line in samplesheet: #step past header lines to data section
			if '[Data]' in line:
				break
		entries = list(csv.DictReader(samplesheet, delimiter=','))
		for entry, index in zip(entries, range(1, len(entries) + 1)):
			if 'SAMN' in entry['Sample_Name']:
				entry['Sample Name'] = entry['organism'] = entry['Biosample Accession'] = entry['Sample_Name']
			elif 'SAMN' in entry['Sample_ID']:
				entry['Biosample Accession'] = entry['Sample_ID']
				entry['Sample Name'] = entry['organism'] = entry['Sample_Name']
			else:
				print "Can't submit sample {Sample_Name}, no NCBI BioSample ID.".format(**entry)
				break
			try:
				for file_no in (1, 2):
			
					with open(join(input_dir, 'Data', 'Intensities', 
						'BaseCalls', '{sample}_S{index}_L001_R{file_no}_001.fastq.gz'.format(
							sample=entry['Sample_Name'].replace("_", "-"),
							index=index,
							file_no=file_no
						)),
					'rb'
					) as runfile:
						hash = hashlib.md5()
						line_no = 0
						for line in runfile:
							hash.update(line)
							line_no += 1
							if line_no % 1000 == 0:
								callback(line_no)
						entry['file{}_name'.format(file_no)] = '{sample}_S{index}_L001_R{file_no}_001.fasta.gz'.format(
							sample=entry['Sample_Name'],
							index=index,
							file_no=file_no
						)
						entry['file{}_checksum'.format(file_no)] = hash.hexdigest()
						entry['version'] = version
			except (IOError, OSError) as e:
				print e
				continue
			make_submission(output_dir, entry, project or entry['Sample_Project'], **kwargs)	
				
					
def output_table(path):
	with open(join(path, 'SRA_Quick_Submit_template.txt'), 'w') as template_file:
		for h in ('Sample Name',
				  'organism',
				  'strain',
				  'Biosample Accession',
				  'file1_name',
				  'file1_checksum',
				  'file2_name',
				  'file2_checksum'):
			template_file.write("{}\t".format(h))
		template_file.write("\n")
	print "Wrote {}/SRA_Quick_Submit_template.txt".format(path)
	
if __name__ == "__main__":	
	import argparse
			
	p = argparse.ArgumentParser(description=description, 
								epilog=change_history, 
								argument_default=False,
								formatter_class=argparse.RawDescriptionHelpFormatter)						
	
	p.add_argument('-o', '--output', action='store', 
				   metavar='PATH', 
				   help="Output directory. Will be created if it doesn't already exist. [default: %(default)s]", 
				   default=os.getcwd())
	p.add_argument('-d', '--hold-date', metavar="YYYY-MM-DD", 
				   help="Hold this submission until specified date. SRA allows up to a one-year hold.",
				   action='store',
				   dest='hold')
	p.add_argument('-l', '--delimiter', metavar="CHARACTER", 
				   help="Character used as delimiter in table. [default: \\t]", 
				   action='store', 
				   default='\t')
	p.add_argument('-n', '--name', metavar="NAME", help="Submitter name.", action='store')
	p.add_argument('-e', '--email', metavar="email@email.email", help="Submitter email.", action='store')
	p.add_argument('project', metavar="PRJNAxxxxxxx", action='store')
	p.add_argument('input', metavar="PATH or FILE", action='store')
	
	args = p.parse_args()
	
	if not args.hold:
		args.hold = datetime.datetime.today().strftime("%Y-%m-%d")
		print "No HOLD date specified, using default: {}".format(args.hold)
		
	if not args.name:
		for key in ('USER', 'LOGNAME'):
			try:
				args.name = os.environ[key]
				print "Name not specified; got '{}' from shell environment".format(args.name)
				break
			except KeyError:
				pass
		if not args.name:
			print """No name given and $USER/$LOGNAME vars not set. Specify submitter name with -n "My Name"."""
			quit()
			
	if not args.email:
		try:
			args.email = os.environ['USER_PRINCIPAL_NAME']
			print "Email not specified; got '{}' from shell environment".format(args.email)
		except KeyError:
			print "No email given and $USER_PRINCIPAL_NAME var not set. Specify submitter email with -e email@email.email"
			quit()
	if isdir(args.input):
		def cb(s):
			print "{}\r".format(s),
		process_miseq_output(abspath(args.input), abspath(args.output), callback=cb, **vars(args))
	else:		
		try:
			with open(abspath(args.input), 'rU') as input_file:
				entries = csv.DictReader(input_file, dialect='excel', delimiter=delimiter)
				for entry in entries:
					make_submission(abspath(args.output), entry, **vars(args))
		except IndexError:
			print "No metadata file specified."
			print usage
			quit()
		except IOError:
			print "{} not found. Check file location and try again.".format(sys.argv[1])
			quit()
		
	
	

